<wsdl:definitions targetNamespace="http://main.jws.com.hanel.de">
	<wsdl:documentation>
		Webservice V 2.1/6 STANDARD on MP12N-H[HOST-WEB] / MP14-H[HOST-WEB]
	</wsdl:documentation>
	<wsdl:types>
		<xs:schema attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://main.jws.com.hanel.de/xsd">
			<xs:complexType name="ResultReadStatus">
				<xs:sequence>
					<xs:element minOccurs="0" name="accessNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="accessSide" type="xs:int"/>
					<xs:element minOccurs="0" name="compDepths" type="xs:int"/>
					<xs:element minOccurs="0" name="compartments" type="xs:int"/>
					<xs:element minOccurs="0" name="imbalanceDirection" nillable="true" type="xs:string"/>
					<xs:element minOccurs="0" name="imbalanceShelf" type="xs:int"/>
					<xs:element minOccurs="0" name="komNumber" nillable="true" type="xs:string"/>
					<xs:element minOccurs="0" name="liftNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="liftType" type="xs:int"/>
					<xs:element minOccurs="0" name="returnValue" type="xs:int"/>
					<xs:element minOccurs="0" name="shelfInAccess" type="xs:int"/>
					<xs:element minOccurs="0" name="shelfTable" nillable="true" type="xs:string"/>
					<xs:element minOccurs="0" name="browserVersion" type="xs:int"/>
					<xs:element minOccurs="0" name="doorStatus" type="xs:int"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="ResultReadStatusV02">
				<xs:sequence>
					<xs:element minOccurs="0" name="accessNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="accessSide" type="xs:int"/>
					<xs:element minOccurs="0" name="compDepths" type="xs:int"/>
					<xs:element minOccurs="0" name="compartments" type="xs:int"/>
					<xs:element minOccurs="0" name="imbalanceDirection" nillable="true" type="xs:string"/>
					<xs:element minOccurs="0" name="imbalanceShelf" type="xs:int"/>
					<xs:element minOccurs="0" name="komNumber" nillable="true" type="xs:string"/>
					<xs:element minOccurs="0" name="liftNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="liftType" type="xs:int"/>
					<xs:element minOccurs="0" name="returnValue" type="xs:int"/>
					<xs:element minOccurs="0" name="shelfInAccess" type="xs:int"/>
					<xs:element minOccurs="0" name="shelfTable" nillable="true" type="xs:string"/>
					<xs:element minOccurs="0" name="browserVersion" type="xs:int"/>
					<xs:element minOccurs="0" name="doorStatus" type="xs:int"/>
					<xs:element minOccurs="0" name="mpControl" type="xs:int"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="ResultConfirmV01">
				<xs:sequence>
					<xs:element minOccurs="0" name="returnValue" type="xs:int"/>
					<xs:element minOccurs="0" name="liftNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="accessNumber" type="xs:int"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="RequestGetShelf">
				<xs:sequence>
					<xs:element minOccurs="1" name="pm01_shelfNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="pm02_compartmentNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="pm03_compartmentDepthNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="pm04_containerWidthInCompartment" type="xs:int"/>
					<xs:element minOccurs="0" name="pm05_containerWidthInCompartmentDepth" type="xs:int"/>
					<xs:element minOccurs="0" name="pm10_compartmentNumberPickOLight" type="xs:int"/>
					<xs:element minOccurs="0" name="pm11_compartmentDepthNumberPickOLight" type="xs:int"/>
					<xs:element minOccurs="0" name="pm12_compartmentMMPickOLight" type="xs:int"/>
					<xs:element minOccurs="0" name="pm13_compartmentDepthMMPickOLight" type="xs:int"/>
					<xs:element minOccurs="0" name="pm15_shelfLocking" type="xs:int"/>
					<xs:element minOccurs="0" name="pm16_doorHeight" type="xs:int"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="ResultGetShelf">
				<xs:sequence>
					<xs:element minOccurs="0" name="accessNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="imbalanceDirection" nillable="true" type="xs:string"/>
					<xs:element minOccurs="0" name="imbalanceShelf" type="xs:int"/>
					<xs:element minOccurs="0" name="liftNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="returnValue" type="xs:int"/>
					<xs:element minOccurs="0" name="shelfHeight" type="xs:int"/>
					<xs:element minOccurs="0" name="shelfInAccess" type="xs:int"/>
					<xs:element minOccurs="0" name="shelfWithHeight" type="xs:int"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="RequestGetShelfV02">
				<xs:sequence>
					<xs:element minOccurs="1" name="pm01_shelfNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="pm02_compartmentNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="pm03_compartmentDepthNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="pm04_containerWidthInCompartment" type="xs:int"/>
					<xs:element minOccurs="0" name="pm05_containerWidthInCompartmentDepth" type="xs:int"/>
					<xs:element minOccurs="0" name="pm06_textLine1" nillable="true" type="xs:string"/>
					<xs:element minOccurs="0" name="pm07_textLine2" nillable="true" type="xs:string"/>
					<xs:element minOccurs="0" name="pm08_textLine3" nillable="true" type="xs:string"/>
					<xs:element minOccurs="0" name="pm09_textLine4" nillable="true" type="xs:string"/>
					<xs:element minOccurs="0" name="pm10_compartmentNumberPickOLight" type="xs:int"/>
					<xs:element minOccurs="0" name="pm11_compartmentDepthNumberPickOLight" type="xs:int"/>
					<xs:element minOccurs="0" name="pm12_compartmentMMPickOLight" type="xs:int"/>
					<xs:element minOccurs="0" name="pm13_compartmentDepthMMPickOLight" type="xs:int"/>
					<xs:element minOccurs="0" name="pm15_shelfLocking" type="xs:int"/>
					<xs:element minOccurs="0" name="pm16_doorHeight" type="xs:int"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="RequestBaseServices">
				<xs:sequence>
					<xs:element minOccurs="0" name="pm01_addShelf" type="xs:int"/>
					<xs:element minOccurs="0" name="pm02_removeShelf" type="xs:int"/>
					<xs:element minOccurs="0" name="pm03_getShelf" type="xs:int"/>
					<xs:element minOccurs="0" name="pm04_storeShelf" type="xs:int"/>
					<xs:element minOccurs="0" name="pm05_startOptimisationRun" type="xs:int"/>
					<xs:element minOccurs="0" name="pm06_releaseShelfLocking" type="xs:int"/>
					<xs:element minOccurs="0" name="pm11_manualShelfPositioningByNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="pm12_manualShelfSelectionBySight" type="xs:int"/>
					<xs:element minOccurs="0" name="pm21_infoServices" type="xs:int"/>
					<xs:element minOccurs="0" name="pm22_systemServices" type="xs:int"/>
					<xs:element minOccurs="0" name="pm23_slidingDoor" type="xs:int"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="RequestBaseServicesV02">
				<xs:sequence>
					<xs:element minOccurs="0" name="pm01_addShelf" type="xs:int"/>
					<xs:element minOccurs="0" name="pm02_removeShelf" type="xs:int"/>
					<xs:element minOccurs="0" name="pm03_getShelf" type="xs:int"/>
					<xs:element minOccurs="0" name="pm04_storeShelf" type="xs:int"/>
					<xs:element minOccurs="0" name="pm05_startOptimisationRun" type="xs:int"/>
					<xs:element minOccurs="0" name="pm06_releaseShelfLocking" type="xs:int"/>
					<xs:element minOccurs="0" name="pm11_manualShelfPositioningByNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="pm12_manualShelfSelectionBySight" type="xs:int"/>
					<xs:element minOccurs="0" name="pm22_systemServices" type="xs:int"/>
					<xs:element minOccurs="0" name="pm23_slidingDoor" type="xs:int"/>
					<xs:element minOccurs="0" name="pm24_shelfTransfer" type="xs:int"/>
					<xs:element minOccurs="0" name="pm25_runStorageLocation" type="xs:int"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="ResultBaseServices">
				<xs:sequence>
					<xs:element minOccurs="0" name="accessNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="imbalanceDirection" nillable="true" type="xs:string"/>
					<xs:element minOccurs="0" name="imbalanceShelf" type="xs:int"/>
					<xs:element minOccurs="0" name="liftNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="returnValue" type="xs:int"/>
					<xs:element minOccurs="0" name="shelfInAccess" type="xs:int"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="ResultStoreShelf">
				<xs:sequence>
					<xs:element minOccurs="0" name="returnValue" type="xs:int"/>
					<xs:element minOccurs="0" name="liftNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="accessNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="shelfInAccess" type="xs:int"/>
					<xs:element minOccurs="0" name="shelfWithHeight" type="xs:int"/>
					<xs:element minOccurs="0" name="shelfHeight" type="xs:int"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="RequestAddShelf">
				<xs:sequence>
					<xs:element minOccurs="1" name="pm01_shelfNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="pm02_shelfHeight" type="xs:int"/>
					<xs:element minOccurs="0" name="pm03_shelfSpeed" type="xs:int"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="ResultAddShelf">
				<xs:sequence>
					<xs:element minOccurs="0" name="returnValue" type="xs:int"/>
					<xs:element minOccurs="0" name="liftNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="accessNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="shelfInAccess" type="xs:int"/>
					<xs:element minOccurs="0" name="shelfWithHeight" type="xs:int"/>
					<xs:element minOccurs="0" name="shelfHeight" type="xs:int"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="RequestRemoveShelf">
				<xs:sequence>
					<xs:element minOccurs="1" name="pm01_shelfNumber" type="xs:int"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="ResultRemoveShelf">
				<xs:sequence>
					<xs:element minOccurs="0" name="returnValue" type="xs:int"/>
					<xs:element minOccurs="0" name="liftNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="accessNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="shelfInAccess" type="xs:int"/>
					<xs:element minOccurs="0" name="shelfWithHeight" type="xs:int"/>
					<xs:element minOccurs="0" name="shelfHeight" type="xs:int"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="RequestOptimisationRun">
				<xs:sequence>
					<xs:element minOccurs="1" name="pm01_optimisationType" type="xs:int"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="ResultOptimisationRun">
				<xs:sequence>
					<xs:element minOccurs="0" name="returnValue" type="xs:int"/>
					<xs:element minOccurs="0" name="liftNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="accessNumber" type="xs:int"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="ResultDeleteCompDisp">
				<xs:sequence>
					<xs:element minOccurs="0" name="returnValue" type="xs:int"/>
					<xs:element minOccurs="0" name="liftNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="accessNumber" type="xs:int"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="RequestSetInterface">
				<xs:sequence>
					<xs:element minOccurs="1" name="pm01_device" type="xs:int"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="ResultSetInterface">
				<xs:sequence>
					<xs:element minOccurs="0" name="returnValue" type="xs:int"/>
					<xs:element minOccurs="0" name="liftNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="accessNumber" type="xs:int"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="ResultReadStMpMod">
				<xs:sequence>
					<xs:element minOccurs="0" name="returnValue" type="xs:int"/>
					<xs:element minOccurs="0" name="liftNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="accessNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="shelfPrePositioning" type="xs:int"/>
					<xs:element minOccurs="0" name="storageLocationHeight" type="xs:int"/>
					<xs:element minOccurs="0" name="adjustableShelfSpeed" type="xs:int"/>
					<xs:element minOccurs="0" name="remoteControlling" type="xs:int"/>
					<xs:element minOccurs="0" name="intermediateShelfBuffer" type="xs:int"/>
					<xs:element minOccurs="0" name="shelfTransfer" type="xs:int"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="ResultReadStLftFeat">
				<xs:sequence>
					<xs:element minOccurs="0" name="returnValue" type="xs:int"/>
					<xs:element minOccurs="0" name="liftNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="accessNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="pickOLightVariable" type="xs:int"/>
					<xs:element minOccurs="0" name="automaticSlidingDoor" type="xs:int"/>
					<xs:element minOccurs="0" name="integratedSignalIndicators" type="xs:int"/>
					<xs:element minOccurs="0" name="requisitionLedge" type="xs:int"/>
					<xs:element minOccurs="0" name="numberOfConfirmationModules" type="xs:int"/>
					<xs:element minOccurs="0" name="shelfLocking" type="xs:int"/>
					<xs:element minOccurs="0" name="accessCodeManagement" type="xs:int"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="RetReadStLftFeatV02">
				<xs:sequence>
					<xs:element minOccurs="0" name="returnValue" type="xs:int"/>
					<xs:element minOccurs="0" name="liftNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="accessNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="pickOLightVariable" type="xs:int"/>
					<xs:element minOccurs="0" name="automaticSlidingDoor" type="xs:int"/>
					<xs:element minOccurs="0" name="integratedSignalIndicators" type="xs:int"/>
					<xs:element minOccurs="0" name="requisitionLedge" type="xs:int"/>
					<xs:element minOccurs="0" name="numberOfConfirmationModules" type="xs:int"/>
					<xs:element minOccurs="0" name="shelfLocking" type="xs:int"/>
					<xs:element minOccurs="0" name="accessCodeManagement" type="xs:int"/>
					<xs:element minOccurs="0" name="numberOfShelfsWithPowerSockets" type="xs:int"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="ResultCloseDoor">
				<xs:sequence>
					<xs:element minOccurs="0" name="returnValue" type="xs:int"/>
					<xs:element minOccurs="0" name="liftNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="accessNumber" type="xs:int"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="RequestSetSignal">
				<xs:sequence>
					<xs:element minOccurs="0" name="pm01_signal1" type="xs:int"/>
					<xs:element minOccurs="0" name="pm02_signal2" type="xs:int"/>
					<xs:element minOccurs="0" name="pm03_signal3" type="xs:int"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="ResultSetSignal">
				<xs:sequence>
					<xs:element minOccurs="0" name="returnValue" type="xs:int"/>
					<xs:element minOccurs="0" name="liftNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="accessNumber" type="xs:int"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="RequestConfReqLedge">
				<xs:sequence>
					<xs:element minOccurs="1" name="pm01_confirmModuleNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="pm02_textLine1" nillable="true" type="xs:string"/>
					<xs:element minOccurs="0" name="pm03_textLine2" nillable="true" type="xs:string"/>
					<xs:element minOccurs="0" name="pm04_textLine3" nillable="true" type="xs:string"/>
					<xs:element minOccurs="0" name="pm05_quantity" type="xs:int"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="RequestConfReqLedgeV02">
				<xs:sequence>
					<xs:element minOccurs="1" name="pm01_confirmModuleNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="pm02_textLine1" nillable="true" type="xs:string"/>
					<xs:element minOccurs="0" name="pm03_textLine2" nillable="true" type="xs:string"/>
					<xs:element minOccurs="0" name="pm04_textLine3" nillable="true" type="xs:string"/>
					<xs:element minOccurs="0" name="pm05_quantity" type="xs:int"/>
					<xs:element minOccurs="0" name="pm06_onlyText" type="xs:int"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="ResultConfReqLedge">
				<xs:sequence>
					<xs:element minOccurs="0" name="returnValue" type="xs:int"/>
					<xs:element minOccurs="0" name="liftNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="accessNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="corrQuantity" type="xs:int"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="ResultConfReqLedgeV02">
				<xs:sequence>
					<xs:element minOccurs="0" name="returnValue" type="xs:int"/>
					<xs:element minOccurs="0" name="liftNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="accessNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="corrQuantity" type="xs:int"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="RequestPrePosMode">
				<xs:sequence>
					<xs:element minOccurs="1" name="pm01_prePosMode" type="xs:int"/>
					<xs:element minOccurs="1" name="pg03_cancelUrl" nillable="false" type="xs:string"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="ResultPrePosMode">
				<xs:sequence>
					<xs:element minOccurs="0" name="returnValue" type="xs:int"/>
					<xs:element minOccurs="0" name="liftNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="accessNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="shelfInAccess" type="xs:int"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="RequestReadStHeight">
				<xs:sequence>
					<xs:element minOccurs="1" name="pm01_stringNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="pm02_typeOfHeight" type="xs:int"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="ResultReadStHeight">
				<xs:sequence>
					<xs:element minOccurs="0" name="returnValue" type="xs:int"/>
					<xs:element minOccurs="0" name="liftNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="accessNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="stringNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="stringOfHeight" nillable="true" type="xs:string"/>
					<xs:element minOccurs="0" name="fixedShelfHeight" type="xs:int"/>
					<xs:element minOccurs="0" name="shelfHeightMonitor" type="xs:int"/>
					<xs:element minOccurs="0" name="minShelfHeight" type="xs:int"/>
					<xs:element minOccurs="0" name="maxShelfHeight" type="xs:int"/>
					<xs:element minOccurs="0" name="carrierIncrement" type="xs:int"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="RequestEditShelfProp">
				<xs:sequence>
					<xs:element minOccurs="1" name="pm01_shelfNumber" type="xs:int"/>
					<xs:element minOccurs="1" name="pm02_shelfTargetHeight" type="xs:int"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="ResultEditShelfProp">
				<xs:sequence>
					<xs:element minOccurs="0" name="returnValue" type="xs:int"/>
					<xs:element minOccurs="0" name="liftNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="accessNumber" type="xs:int"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="RequestReadStSpeed">
				<xs:sequence>
					<xs:element minOccurs="1" name="pm01_stringNumber" type="xs:int"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="ResultReadStSpeed">
				<xs:sequence>
					<xs:element minOccurs="0" name="returnValue" type="xs:int"/>
					<xs:element minOccurs="0" name="liftNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="accessNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="stringNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="stringOfSpeed" nillable="true" type="xs:string"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="RequestGetShelfBackgr">
				<xs:sequence>
					<xs:element minOccurs="1" name="pm01_shelfNumber" type="xs:int"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="ResultGetShelfBackgr">
				<xs:sequence>
					<xs:element minOccurs="0" name="returnValue" type="xs:int"/>
					<xs:element minOccurs="0" name="liftNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="accessNumber" type="xs:int"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="RequestSetStartUrl">
				<xs:sequence>
					<xs:element minOccurs="1" name="pm01_startUrl" nillable="true" type="xs:string"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="ResultSetStartUrl">
				<xs:sequence>
					<xs:element minOccurs="0" name="returnValue" type="xs:int"/>
					<xs:element minOccurs="0" name="liftNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="accessNumber" type="xs:int"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="RequestShelfTransfer">
				<xs:sequence>
					<xs:element minOccurs="1" name="pm01_destinationAccessNumber" type="xs:int"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="ResultShelfTransfer">
				<xs:sequence>
					<xs:element minOccurs="0" name="liftNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="accessNumber" type="xs:int"/>
					<xs:element minOccurs="0" name="shelfInAccess" type="xs:int"/>
					<xs:element minOccurs="0" name="shelfWithHeight" type="xs:int"/>
					<xs:element minOccurs="0" name="shelfHeight" type="xs:int"/>
					<xs:element minOccurs="0" name="returnValue" type="xs:int"/>
				</xs:sequence>
			</xs:complexType>
		</xs:schema>
		<xs:schema attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://main.jws.com.hanel.de">
			<xs:import namespace="http://main.jws.com.hanel.de/xsd"/>
			<xs:element name="read_status">
				<xs:complexType>
					<xs:sequence/>
				</xs:complexType>
			</xs:element>
			<xs:element name="readStatusV02">
				<xs:complexType>
					<xs:sequence/>
				</xs:complexType>
			</xs:element>
			<xs:element name="read_status_res">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="return" nillable="true" type="ax21:ResultReadStatus"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="readStatusResV02">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="return" nillable="true" type="ax21:ResultReadStatusV02"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="confirmV01">
				<xs:complexType>
					<xs:sequence/>
				</xs:complexType>
			</xs:element>
			<xs:element name="confirmResV01">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="return" nillable="true" type="ax21:ResultConfirmV01"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="get_shelf">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="param" nillable="true" type="ax21:RequestGetShelf"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="get_shelf_res">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="return" nillable="true" type="ax21:ResultGetShelf"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="getShelfV02">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="param" nillable="true" type="ax21:RequestGetShelfV02"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="base_services">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="param" nillable="true" type="ax21:RequestBaseServices"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="base_services_res">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="return" nillable="true" type="ax21:ResultBaseServices"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="base_servicesV02">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="param" nillable="true" type="ax21:RequestBaseServicesV02"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="store_shelf">
				<xs:complexType>
					<xs:sequence/>
				</xs:complexType>
			</xs:element>
			<xs:element name="store_shelf_res">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="return" nillable="true" type="ax21:ResultStoreShelf"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="add_shelf">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="param" nillable="true" type="ax21:RequestAddShelf"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="add_shelf_res">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="return" nillable="true" type="ax21:ResultAddShelf"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="remove_shelf">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="param" nillable="true" type="ax21:RequestRemoveShelf"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="remove_shelf_res">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="return" nillable="true" type="ax21:ResultRemoveShelf"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="optimisation_run">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="param" nillable="true" type="ax21:RequestOptimisationRun"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="optimisation_run_res">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="return" nillable="true" type="ax21:ResultOptimisationRun"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="delete_comp_disp">
				<xs:complexType>
					<xs:sequence/>
				</xs:complexType>
			</xs:element>
			<xs:element name="delete_comp_disp_res">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="return" nillable="true" type="ax21:ResultDeleteCompDisp"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="set_interface">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="param" nillable="true" type="ax21:RequestSetInterface"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="set_interface_res">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="return" nillable="true" type="ax21:ResultSetInterface"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="read_st_mp_mod">
				<xs:complexType>
					<xs:sequence/>
				</xs:complexType>
			</xs:element>
			<xs:element name="read_st_mp_mod_res">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="return" nillable="true" type="ax21:ResultReadStMpMod"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="read_st_lft_feat">
				<xs:complexType>
					<xs:sequence/>
				</xs:complexType>
			</xs:element>
			<xs:element name="readStLftFeatV02">
				<xs:complexType>
					<xs:sequence/>
				</xs:complexType>
			</xs:element>
			<xs:element name="read_st_lft_feat_res">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="return" nillable="true" type="ax21:ResultReadStLftFeat"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="readStLftFeatResV02">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="return" nillable="true" type="ax21:RetReadStLftFeatV02"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="close_door">
				<xs:complexType>
					<xs:sequence/>
				</xs:complexType>
			</xs:element>
			<xs:element name="close_door_res">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="return" nillable="true" type="ax21:ResultCloseDoor"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="set_signal">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="param" nillable="true" type="ax21:RequestSetSignal"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="set_signal_res">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="return" nillable="true" type="ax21:ResultSetSignal"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="conf_req_ledge">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="param" nillable="true" type="ax21:RequestConfReqLedge"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="conf_req_ledge_res">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="return" nillable="true" type="ax21:ResultConfReqLedge"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="confReqLedgeV02">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="param" nillable="true" type="ax21:RequestConfReqLedgeV02"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="confReqLedgeResV02">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="return" nillable="true" type="ax21:ResultConfReqLedgeV02"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="pre_pos_mode">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="param" nillable="true" type="ax21:RequestPrePosMode"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="pre_pos_mode_res">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="return" nillable="true" type="ax21:ResultPrePosMode"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="read_st_height">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="param" nillable="true" type="ax21:RequestReadStHeight"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="read_st_height_res">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="return" nillable="true" type="ax21:ResultReadStHeight"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="edit_shelf_prop">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="param" nillable="true" type="ax21:RequestEditShelfProp"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="edit_shelf_prop_res">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="return" nillable="true" type="ax21:ResultEditShelfProp"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="read_st_speed">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="param" nillable="true" type="ax21:RequestReadStSpeed"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="read_st_speed_res">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="return" nillable="true" type="ax21:ResultReadStSpeed"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="get_shelf_backgr">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="param" nillable="true" type="ax21:RequestGetShelfBackgr"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="get_shelf_backgr_res">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="return" nillable="true" type="ax21:ResultGetShelfBackgr"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="set_start_url">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="param" nillable="true" type="ax21:RequestSetStartUrl"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="set_start_url_res">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="return" nillable="true" type="ax21:ResultSetStartUrl"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="shelf_transfer">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="param" nillable="true" type="ax21:RequestShelfTransfer"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="shelf_transfer_res">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="return" nillable="true" type="ax21:ResultShelfTransfer"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:schema>
	</wsdl:types>
	<wsdl:message name="confirmReqV01">
		<wsdl:part name="parameters" element="ns:confirmV01"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="delete_comp_disp_req">
		<wsdl:part name="parameters" element="ns:delete_comp_disp"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="delete_comp_disp_res">
		<wsdl:part name="parameters" element="ns:delete_comp_disp_res"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="readStatusReqV02">
		<wsdl:part name="parameters" element="ns:readStatusV02"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="getShelfResV02">
		<wsdl:part name="parameters" element="ns:get_shelf_res"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="base_services_reqV02">
		<wsdl:part name="parameters" element="ns:base_servicesV02"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="read_st_mp_mod_req">
		<wsdl:part name="parameters" element="ns:read_st_mp_mod"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="read_st_mp_mod_res">
		<wsdl:part name="parameters" element="ns:read_st_mp_mod_res"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="confReqLedgeResV02">
		<wsdl:part name="parameters" element="ns:confReqLedgeResV02"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="conf_req_ledge_req">
		<wsdl:part name="parameters" element="ns:conf_req_ledge"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="conf_req_ledge_res">
		<wsdl:part name="parameters" element="ns:conf_req_ledge_res"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="store_shelf_req">
		<wsdl:part name="parameters" element="ns:store_shelf"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="get_shelf_res">
		<wsdl:part name="parameters" element="ns:get_shelf_res"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="get_shelf_req">
		<wsdl:part name="parameters" element="ns:get_shelf"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="read_st_speed_req">
		<wsdl:part name="parameters" element="ns:read_st_speed"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="store_shelf_res">
		<wsdl:part name="parameters" element="ns:store_shelf_res"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="read_st_speed_res">
		<wsdl:part name="parameters" element="ns:read_st_speed_res"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="set_interface_res">
		<wsdl:part name="parameters" element="ns:set_interface_res"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="close_door_req">
		<wsdl:part name="parameters" element="ns:close_door"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="optimisation_run_res">
		<wsdl:part name="parameters" element="ns:optimisation_run_res"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="close_door_res">
		<wsdl:part name="parameters" element="ns:close_door_res"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="set_interface_req">
		<wsdl:part name="parameters" element="ns:set_interface"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="shelf_transfer_res">
		<wsdl:part name="parameters" element="ns:shelf_transfer_res"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="add_shelf_req">
		<wsdl:part name="parameters" element="ns:add_shelf"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="readStLftFeatResV02">
		<wsdl:part name="parameters" element="ns:readStLftFeatResV02"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="add_shelf_res">
		<wsdl:part name="parameters" element="ns:add_shelf_res"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="get_shelf_backgr_res">
		<wsdl:part name="parameters" element="ns:get_shelf_backgr_res"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="remove_shelf_res">
		<wsdl:part name="parameters" element="ns:remove_shelf_res"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="readStatusResV02">
		<wsdl:part name="parameters" element="ns:readStatusResV02"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="pre_pos_mode_res">
		<wsdl:part name="parameters" element="ns:pre_pos_mode_res"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="pre_pos_mode_req">
		<wsdl:part name="parameters" element="ns:pre_pos_mode"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="shelf_transfer_req">
		<wsdl:part name="parameters" element="ns:shelf_transfer"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="getShelfReqV02">
		<wsdl:part name="parameters" element="ns:getShelfV02"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="optimisation_run_req">
		<wsdl:part name="parameters" element="ns:optimisation_run"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="confirmResV01">
		<wsdl:part name="parameters" element="ns:confirmResV01"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="confReqLedgeReqV02">
		<wsdl:part name="parameters" element="ns:confReqLedgeV02"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="edit_shelf_prop_res">
		<wsdl:part name="parameters" element="ns:edit_shelf_prop_res"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="edit_shelf_prop_req">
		<wsdl:part name="parameters" element="ns:edit_shelf_prop"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="remove_shelf_req">
		<wsdl:part name="parameters" element="ns:remove_shelf"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="get_shelf_backgr_req">
		<wsdl:part name="parameters" element="ns:get_shelf_backgr"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="read_st_lft_feat_res">
		<wsdl:part name="parameters" element="ns:read_st_lft_feat_res"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="read_status_req">
		<wsdl:part name="parameters" element="ns:read_status"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="read_st_lft_feat_req">
		<wsdl:part name="parameters" element="ns:read_st_lft_feat"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="read_status_res">
		<wsdl:part name="parameters" element="ns:read_status_res"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="base_services_req">
		<wsdl:part name="parameters" element="ns:base_services"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="set_start_url_res">
		<wsdl:part name="parameters" element="ns:set_start_url_res"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="set_start_url_req">
		<wsdl:part name="parameters" element="ns:set_start_url"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="read_st_height_res">
		<wsdl:part name="parameters" element="ns:read_st_height_res"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="readStLftFeatReqV02">
		<wsdl:part name="parameters" element="ns:readStLftFeatV02"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="set_signal_res">
		<wsdl:part name="parameters" element="ns:set_signal_res"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="read_st_height_req">
		<wsdl:part name="parameters" element="ns:read_st_height"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="set_signal_req">
		<wsdl:part name="parameters" element="ns:set_signal"> </wsdl:part>
	</wsdl:message>
	<wsdl:message name="base_services_res">
		<wsdl:part name="parameters" element="ns:base_services_res"> </wsdl:part>
	</wsdl:message>
	<wsdl:portType name="MacroPortType">
		<wsdl:operation name="base_services">
			<wsdl:documentation>Call up basic functions</wsdl:documentation>
			<wsdl:input message="ns:base_services_req" wsaw:Action="urn:base_services"> </wsdl:input>
			<wsdl:output message="ns:base_services_res" wsaw:Action="urn:base_services_res"> </wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="base_servicesV02">
			<wsdl:documentation>Call up basic functions V02</wsdl:documentation>
			<wsdl:input message="ns:base_services_reqV02" wsaw:Action="urn:base_servicesV02"> </wsdl:input>
			<wsdl:output message="ns:base_services_res" wsaw:Action="urn:base_services_res"> </wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="get_shelf">
			<wsdl:documentation>Get shelf with display of storage location</wsdl:documentation>
			<wsdl:input message="ns:get_shelf_req" wsaw:Action="urn:get_shelf"> </wsdl:input>
			<wsdl:output message="ns:get_shelf_res" wsaw:Action="urn:get_shelf_res"> </wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="getShelfV02">
			<wsdl:documentation>
				Get shelf with display of storage location and additional text
			</wsdl:documentation>
			<wsdl:input message="ns:getShelfReqV02" wsaw:Action="urn:getShelfV02"> </wsdl:input>
			<wsdl:output message="ns:getShelfResV02" wsaw:Action="urn:getShelfResV02"> </wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="read_status">
			<wsdl:documentation>Query status information</wsdl:documentation>
			<wsdl:input message="ns:read_status_req" wsaw:Action="urn:read_status"> </wsdl:input>
			<wsdl:output message="ns:read_status_res" wsaw:Action="urn:read_status_res"> </wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="readStatusV02">
			<wsdl:documentation>Query status information V02</wsdl:documentation>
			<wsdl:input message="ns:readStatusReqV02" wsaw:Action="urn:readStatusV02"> </wsdl:input>
			<wsdl:output message="ns:readStatusResV02" wsaw:Action="urn:readStatusResV02"> </wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="confirmV01">
			<wsdl:documentation>Confirm V01</wsdl:documentation>
			<wsdl:input message="ns:confirmReqV01" wsaw:Action="urn:confirmV01"> </wsdl:input>
			<wsdl:output message="ns:confirmResV01" wsaw:Action="urn:confirmResV01"> </wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="store_shelf">
			<wsdl:documentation>Store shelf</wsdl:documentation>
			<wsdl:input message="ns:store_shelf_req" wsaw:Action="urn:store_shelf"> </wsdl:input>
			<wsdl:output message="ns:store_shelf_res" wsaw:Action="urn:store_shelf_res"> </wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="add_shelf">
			<wsdl:documentation>Add shelf</wsdl:documentation>
			<wsdl:input message="ns:add_shelf_req" wsaw:Action="urn:add_shelf"> </wsdl:input>
			<wsdl:output message="ns:add_shelf_res" wsaw:Action="urn:add_shelf_res"> </wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="remove_shelf">
			<wsdl:documentation>Remove shelf</wsdl:documentation>
			<wsdl:input message="ns:remove_shelf_req" wsaw:Action="urn:remove_shelf"> </wsdl:input>
			<wsdl:output message="ns:remove_shelf_res" wsaw:Action="urn:remove_shelf_res"> </wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="optimisation_run">
			<wsdl:documentation>Starting an optimisation run</wsdl:documentation>
			<wsdl:input message="ns:optimisation_run_req" wsaw:Action="urn:optimisation_run"> </wsdl:input>
			<wsdl:output message="ns:optimisation_run_res" wsaw:Action="urn:optimisation_run_res"> </wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="delete_comp_disp">
			<wsdl:documentation>Clear storage location display</wsdl:documentation>
			<wsdl:input message="ns:delete_comp_disp_req" wsaw:Action="urn:delete_comp_disp"> </wsdl:input>
			<wsdl:output message="ns:delete_comp_disp_res" wsaw:Action="urn:delete_comp_disp_res"> </wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="set_interface">
			<wsdl:documentation>Enable the interface for a peripheral device</wsdl:documentation>
			<wsdl:input message="ns:set_interface_req" wsaw:Action="urn:set_interface"> </wsdl:input>
			<wsdl:output message="ns:set_interface_res" wsaw:Action="urn:set_interface_res"> </wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="read_st_mp_mod">
			<wsdl:documentation>Query supplementary modules</wsdl:documentation>
			<wsdl:input message="ns:read_st_mp_mod_req" wsaw:Action="urn:read_st_mp_mod"> </wsdl:input>
			<wsdl:output message="ns:read_st_mp_mod_res" wsaw:Action="read_st_mp_mod_res"> </wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="read_st_lft_feat">
			<wsdl:documentation>Query supplementary features</wsdl:documentation>
			<wsdl:input message="ns:read_st_lft_feat_req" wsaw:Action="urn:read_st_lft_feat"> </wsdl:input>
			<wsdl:output message="ns:read_st_lft_feat_res" wsaw:Action="read_st_lft_feat_res"> </wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="readStLftFeatV02">
			<wsdl:documentation>Query supplementary features Version 2</wsdl:documentation>
			<wsdl:input message="ns:readStLftFeatReqV02" wsaw:Action="urn:readStLftFeatV02"> </wsdl:input>
			<wsdl:output message="ns:readStLftFeatResV02" wsaw:Action="readStLftFeatResV02"> </wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="close_door">
			<wsdl:documentation>
				Close automatic sliding door -> Useable with supplementary feature: Automatic sliding door
			</wsdl:documentation>
			<wsdl:input message="ns:close_door_req" wsaw:Action="urn:close_door"> </wsdl:input>
			<wsdl:output message="ns:close_door_res" wsaw:Action="close_door_res"> </wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="set_signal">
			<wsdl:documentation>
				Activate signal elements of the signal column -> Useable with supplementary feature: Signal column
			</wsdl:documentation>
			<wsdl:input message="ns:set_signal_req" wsaw:Action="urn:set_signal"> </wsdl:input>
			<wsdl:output message="ns:set_signal_res" wsaw:Action="urn:set_signal_res"> </wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="conf_req_ledge">
			<wsdl:documentation>
				Write text and query confirm button of requisition ledge -> Useable with supplementary feature: Requisition ledge
			</wsdl:documentation>
			<wsdl:input message="ns:conf_req_ledge_req" wsaw:Action="urn:conf_req_ledge"> </wsdl:input>
			<wsdl:output message="ns:conf_req_ledge_res" wsaw:Action="urn:conf_req_ledge_res"> </wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="confReqLedgeV02">
			<wsdl:documentation>
				Write text and / or query confirm button of requisition ledge -> Useable with supplementary feature: Requisition ledge
			</wsdl:documentation>
			<wsdl:input message="ns:confReqLedgeReqV02" wsaw:Action="urn:confReqLedgeV02"> </wsdl:input>
			<wsdl:output message="ns:confReqLedgeResV02" wsaw:Action="urn:confReqLedgeResV02"> </wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="pre_pos_mode">
			<wsdl:documentation>
				Switch shelf pre-positioning mode on / off -> Useable with supplementary module: Shelf pre-positioning
			</wsdl:documentation>
			<wsdl:input message="ns:pre_pos_mode_req" wsaw:Action="urn:pre_pos_mode"> </wsdl:input>
			<wsdl:output message="ns:pre_pos_mode_res" wsaw:Action="urn:pre_pos_mode_res"> </wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="read_st_height">
			<wsdl:documentation>
				Query shelf target height -> Useable with supplementary module: Storage location height management
			</wsdl:documentation>
			<wsdl:input message="ns:read_st_height_req" wsaw:Action="urn:read_st_height"> </wsdl:input>
			<wsdl:output message="ns:read_st_height_res" wsaw:Action="urn:read_st_height_res"> </wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="edit_shelf_prop">
			<wsdl:documentation>
				Edit shelf Height -> Useable with supplementary module: Storage location height management
			</wsdl:documentation>
			<wsdl:input message="ns:edit_shelf_prop_req" wsaw:Action="urn:edit_shelf_prop"> </wsdl:input>
			<wsdl:output message="ns:edit_shelf_prop_res" wsaw:Action="urn:edit_shelf_prop_res"> </wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="read_st_speed">
			<wsdl:documentation>
				Query shelf speed -> Useable with supplementary module: Adjustable shelf speed
			</wsdl:documentation>
			<wsdl:input message="ns:read_st_speed_req" wsaw:Action="urn:read_st_speed"> </wsdl:input>
			<wsdl:output message="ns:read_st_speed_res" wsaw:Action="urn:read_st_speed_res"> </wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="get_shelf_backgr">
			<wsdl:documentation>
				Get shelf in background to intermediate shelf buffer -> Useable with supplementary module: Intermediate shelf buffer for requisition / job processing
			</wsdl:documentation>
			<wsdl:input message="ns:get_shelf_backgr_req" wsaw:Action="urn:get_shelf_backgr"> </wsdl:input>
			<wsdl:output message="ns:get_shelf_backgr_res" wsaw:Action="urn:get_shelf_backgr_res"> </wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="set_start_url">
			<wsdl:documentation>Set new Start URL</wsdl:documentation>
			<wsdl:input message="ns:set_start_url_req" wsaw:Action="urn:set_start_url"> </wsdl:input>
			<wsdl:output message="ns:set_start_url_res" wsaw:Action="urn:set_start_url_res"> </wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="shelf_transfer">
			<wsdl:documentation>Send shelf into another access point</wsdl:documentation>
			<wsdl:input message="ns:shelf_transfer_req" wsaw:Action="urn:shelf_transfer"> </wsdl:input>
			<wsdl:output message="ns:shelf_transfer_res" wsaw:Action="urn:shelf_transfer_res"> </wsdl:output>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="MacroSoap11Binding" type="ns:MacroPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="base_services">
			<soap:operation soapAction="urn:base_services" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="base_servicesV02">
			<soap:operation soapAction="urn:base_servicesV02" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="read_status">
			<soap:operation soapAction="urn:read_status" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="readStatusV02">
			<soap:operation soapAction="urn:readStatusV02" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="confirmV01">
			<soap:operation soapAction="urn:confirmV01" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="get_shelf">
			<soap:operation soapAction="urn:get_shelf" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="getShelfV02">
			<soap:operation soapAction="urn:getShelfV02" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="store_shelf">
			<soap:operation soapAction="urn:store_shelf" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="add_shelf">
			<soap:operation soapAction="urn:add_shelf" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="remove_shelf">
			<soap:operation soapAction="urn:remove_shelf" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="optimisation_run">
			<soap:operation soapAction="urn:optimisation_run" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="delete_comp_disp">
			<soap:operation soapAction="urn:delete_comp_disp" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="set_interface">
			<soap:operation soapAction="urn:set_interface" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="read_st_mp_mod">
			<soap:operation soapAction="urn:read_st_mp_mod" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="read_st_lft_feat">
			<soap:operation soapAction="urn:read_st_lft_feat" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="readStLftFeatV02">
			<soap:operation soapAction="urn:readStLftFeatV02" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="close_door">
			<soap:operation soapAction="urn:close_door" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="set_signal">
			<soap:operation soapAction="urn:set_signal" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="conf_req_ledge">
			<soap:operation soapAction="urn:conf_req_ledge" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="confReqLedgeV02">
			<soap:operation soapAction="urn:confReqLedgeV02" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="pre_pos_mode">
			<soap:operation soapAction="urn:pre_pos_mode" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="read_st_height">
			<soap:operation soapAction="urn:read_st_height" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="edit_shelf_prop">
			<soap:operation soapAction="urn:edit_shelf_prop" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="read_st_speed">
			<soap:operation soapAction="urn:read_st_speed" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="get_shelf_backgr">
			<soap:operation soapAction="urn:get_shelf_backgr" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="set_start_url">
			<soap:operation soapAction="urn:set_start_url" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="shelf_transfer">
			<soap:operation soapAction="urn:shelf_transfer" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="Macro">
		<wsdl:documentation>
			Webservice interface between Haenel MP12N-H[HOST-WEB] / MP14-H[HOST-WEB] controls and Hostsystems
		</wsdl:documentation>
		<wsdl:port name="MacroHttpSoap11Endpoint" binding="ns:MacroSoap11Binding">
			<soap:address location="http://192.168.50.2/jwsmacro/services/Macro.MacroHttpSoap11Endpoint/"/>
		</wsdl:port>
		<wsdl:port name="MacroHttpsSoap11Endpoint" binding="ns:MacroSoap11Binding">
			<soap:address location="https://192.168.50.2/jwsmacro/services/Macro.MacroHttpsSoap11Endpoint/"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
